language: node_js

# TODO when using lts/fermium then node v14.18.2 and npm 6.14.15 is used and we get strange errors. Force using npm 8.1.0
node_js:
  - 16

global:
    # include $HOME for aws command
    - PATH=$HOME/.local/bin:$PATH
    # provide secret keys, so that awscli understands them
    - travis encrypt AWS_ACCESS_KEY_ID=$S3_KEY_ID --add
    - travis encrypt AWS_SECRET_ACCESS_KEY=$S3_KEY --add

script:
    - echo "$CONFIG_CONTENT" > config-local.js
    - npm run build-debug && npm run test

# install awscli command line tool to sync files to s3
before_deploy: pip install --user awscli

deploy:
    on:
        all_branches: master
    skip_cleanup: true
    provider: script
    script:
        # upload all files from ./dist folder and delete files on s3 which are not in current build
        - aws s3 sync ./dist s3://gh-maps-react/$TRAVIS_BRANCH --delete
